version: '3'
services:
  dns:
    image: manfromdownunder/lancachenet-lancache-dns:latest  ## Pulling DNS server for arm
    env_file: .env
    ports:
      - ${DNS_BIND_IP}:53:53/udp
      volumes:
      - /dev/null:/var/log/named/queries.log
      - /dev/null:/var/log/named/queries.log.0
      - /dev/null:/var/log/named/queries.log.1
      - /dev/null:/var/log/named/queries.log.2
    restart: always
  monolithic:
    image: manfromdownunder/lancachenet-monolithic:latest ## Pulling monolithic for arm
    env_file: .env
    ports:
      - 80:80/tcp
    restart: always
    volumes:
      - ${CACHE_ROOT}/cache:/data/cache
      - ${CACHE_ROOT}/logs:-dev/null
